#!/usr/bin/env bash
mvn test;
clear;
echo "#########################################################################################";
echo "cat ./src/test/deca/demo/multiple_print.deca";
echo "#########################################################################################";
cat ./src/test/deca/demo/multiple_print.deca;
read -n 1 -s -r -p "";
echo "#########################################################################################";
echo "test_synt ./src/test/deca/demo/multiple_print.deca";
echo "#########################################################################################";
test_synt ./src/test/deca/demo/multiple_print.deca;
read -n 1 -s -r -p "";
echo "#########################################################################################";
echo "decac ./src/test/deca/demo/multiple_print.deca -p";
echo "#########################################################################################";
decac ./src/test/deca/demo/multiple_print.deca -p;
read -n 1 -s -r -p "";
echo "#########################################################################################";
echo "test_context ./src/test/deca/demo/multiple_print.deca";
echo "#########################################################################################";
test_context ./src/test/deca/demo/multiple_print.deca;
read -n 1 -s -r -p "";
echo "#########################################################################################";
echo "decac ./src/test/deca/demo/multiple_print.deca";
echo "cat ./src/test/deca/demo/multiple_print.ass";
echo "#########################################################################################";
decac ./src/test/deca/demo/multiple_print.deca;
cat ./src/test/deca/demo/multiple_print.ass;
read -n 1 -s -r -p "";
echo "#########################################################################################";
echo "ima ./src/test/deca/demo/multiple_print.ass";
echo "#########################################################################################";
ima ./src/test/deca/demo/multiple_print.ass;
read -n 1 -s -r -p "";
