#!/usr/bin/env bash
mvn test;
clear;
echo "#########################################################################################";
echo "cat ./src/test/deca/demo/sans_objet.deca";
echo "#########################################################################################";
cat ./src/test/deca/demo/sans_objet.deca;
read -n 1 -s -r -p "";
echo "#########################################################################################";
echo "test_synt ./src/test/deca/demo/sans_objet.deca";
echo "#########################################################################################";
test_synt ./src/test/deca/demo/sans_objet.deca;
read -n 1 -s -r -p "";
echo "#########################################################################################";
echo "decac ./src/test/deca/demo/sans_objet.deca -p";
echo "#########################################################################################";
decac ./src/test/deca/demo/sans_objet.deca -p;
read -n 1 -s -r -p "";
echo "#########################################################################################";
echo "decac ./src/test/deca/demo/sans_objet.deca -v";
echo "#########################################################################################";
decac ./src/test/deca/demo/sans_objet.deca -v;
