#!/usr/bin/env bash
clear;
echo "#########################################################################################";
echo "#                ARBRE ABSTRAIT - test_synt ./demo/validation.deca                      #";
echo "#########################################################################################";
read -n 1 -s -r -p "";
test_synt ./demo/validation.deca;
read -n 1 -s -r -p "";
echo "";
echo "#########################################################################################";
echo "#                    DECOMPILATION - decac ./demo/validation.deca -p                    #";
echo "#########################################################################################";
read -n 1 -s -r -p "";
decac ./demo/validation.deca -p;
read -n 1 -s -r -p "";
echo "";
echo "#########################################################################################";
echo "              ARBRE ENRICHI ET DECORE - test_context ./demo/validation.deca             #";
echo "#########################################################################################";
read -n 1 -s -r -p "";
test_context ./demo/validation.deca;
read -n 1 -s -r -p "";
echo "";
echo "#########################################################################################";
echo "#                 FICHIER ASSEMBLEUR - decac ./demo/validation.deca -r 4                #";
echo "#########################################################################################";
read -n 1 -s -r -p "";
decac ./demo/validation.deca -r 4;
cat ./demo/validation.ass;
read -n 1 -s -r -p "";
echo "";
echo "#########################################################################################";
echo "                    EXECUTER ASSEMBLEUR - ima ./demo/validation.ass                     #";
echo "#########################################################################################";
read -n 1 -s -r -p "";
decac ./demo/validation.deca -r 4;
ima ./demo/validation.ass;
read -n 1 -s -r -p "";
